/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { Generate_function_callsRequestBuilderRequestsMetadata, type Generate_function_callsRequestBuilder } from './generate_function_calls/index.js';
// @ts-ignore
import { Generate_planRequestBuilderRequestsMetadata, type Generate_planRequestBuilder } from './generate_plan/index.js';
// @ts-ignore
import { apiClientProxifier, registerDefaultDeserializer, registerDefaultSerializer, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';
// @ts-ignore
import { FormParseNodeFactory, FormSerializationWriterFactory } from '@microsoft/kiota-serialization-form';
// @ts-ignore
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';
// @ts-ignore
import { MultipartSerializationWriterFactory } from '@microsoft/kiota-serialization-multipart';
// @ts-ignore
import { TextParseNodeFactory, TextSerializationWriterFactory } from '@microsoft/kiota-serialization-text';

/**
 * Instantiates a new {@link PostsClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createPostsClient(requestAdapter: RequestAdapter) {
    registerDefaultSerializer(JsonSerializationWriterFactory);
    registerDefaultSerializer(TextSerializationWriterFactory);
    registerDefaultSerializer(FormSerializationWriterFactory);
    registerDefaultSerializer(MultipartSerializationWriterFactory);
    registerDefaultDeserializer(JsonParseNodeFactory);
    registerDefaultDeserializer(TextParseNodeFactory);
    registerDefaultDeserializer(FormParseNodeFactory);
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === null || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "http://127.0.0.1:8000";
    }
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<PostsClient>(requestAdapter, pathParameters, PostsClientNavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface PostsClient extends BaseRequestBuilder<PostsClient> {
    /**
     * The generate_function_calls property
     */
    get generate_function_calls(): Generate_function_callsRequestBuilder;
    /**
     * The generate_plan property
     */
    get generate_plan(): Generate_planRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PostsClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PostsClientNavigationMetadata: Record<Exclude<keyof PostsClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    generate_function_calls: {
        requestsMetadata: Generate_function_callsRequestBuilderRequestsMetadata,
    },
    generate_plan: {
        requestsMetadata: Generate_planRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
