/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAgentExecutionPlanSchemaFromDiscriminatorValue, createHTTPValidationErrorFromDiscriminatorValue, serializeAgentExecutionPlanSchema, serializeGeneratePlanRequest, type AgentExecutionPlanSchema, type GeneratePlanRequest, type HTTPValidationError } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /generate_plan
 */
export interface Generate_planRequestBuilder extends BaseRequestBuilder<Generate_planRequestBuilder> {
    /**
     * Generate Plan
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AgentExecutionPlanSchema>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: GeneratePlanRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AgentExecutionPlanSchema | undefined>;
    /**
     * Generate Plan
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: GeneratePlanRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Generate_planRequestBuilderUriTemplate = "{+baseurl}/generate_plan";
/**
 * Metadata for all the requests in the request builder.
 */
export const Generate_planRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Generate_planRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAgentExecutionPlanSchemaFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeGeneratePlanRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
