/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFunctionCallBlackboardOutputFromDiscriminatorValue, createHTTPValidationErrorFromDiscriminatorValue, serializeFunctionCallBlackboardOutput, serializeFunctionCallGenerateRequest, type FunctionCallBlackboardOutput, type FunctionCallGenerateRequest, type HTTPValidationError } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /generate_function_calls
 */
export interface Generate_function_callsRequestBuilder extends BaseRequestBuilder<Generate_function_callsRequestBuilder> {
    /**
     * Generate Function Calls
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FunctionCallBlackboardOutput>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: FunctionCallGenerateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FunctionCallBlackboardOutput | undefined>;
    /**
     * Generate Function Calls
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: FunctionCallGenerateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Generate_function_callsRequestBuilderUriTemplate = "{+baseurl}/generate_function_calls";
/**
 * Metadata for all the requests in the request builder.
 */
export const Generate_function_callsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Generate_function_callsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createFunctionCallBlackboardOutputFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeFunctionCallGenerateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
